// Custom Roblox / executor-UI blocks, plus the two toolboxes. Standard blocks
// (if, loops, math, text, variables) come from Blockly and are generated by its
// official Lua generator; only the Roblox-specific blocks are defined here.

Blockly.defineBlocksWithJsonArray([
  {
    type: "rbx_print", message0: "print %1",
    args0: [{ type: "input_value", name: "TEXT" }],
    previousStatement: null, nextStatement: null, inputsInline: true,
    colour: 200, tooltip: "Print a line to the executor console / server output",
  },
  {
    type: "rbx_warn", message0: "warn %1",
    args0: [{ type: "input_value", name: "TEXT" }],
    previousStatement: null, nextStatement: null, inputsInline: true,
    colour: 200, tooltip: "Warn (yellow output)",
  },
  {
    type: "rbx_wait", message0: "wait %1 seconds",
    args0: [{ type: "input_value", name: "SECONDS", check: "Number" }],
    previousStatement: null, nextStatement: null, inputsInline: true,
    colour: 40, tooltip: "Yield for a number of seconds",
  },
  {
    type: "rbx_for_each_player", message0: "for each player %1", args0: [{ type: "input_dummy" }],
    message1: "do %1", args1: [{ type: "input_statement", name: "DO" }],
    previousStatement: null, nextStatement: null,
    colour: 270, tooltip: "Loop over every player. Use the 'current player' block inside.",
  },
  {
    type: "rbx_current_player", message0: "current player", output: null,
    colour: 270, tooltip: "The player from the surrounding 'for each player' loop",
  },
  {
    type: "rbx_find_player", message0: "player named %1",
    args0: [{ type: "input_value", name: "NAME", check: "String" }],
    output: null, inputsInline: true,
    colour: 270, tooltip: "Find a player by name (or nil)",
  },
  {
    type: "rbx_players_count", message0: "player count", output: "Number",
    colour: 270, tooltip: "How many players are in the server",
  },
  {
    type: "rbx_kick", message0: "kick %1 reason %2",
    args0: [{ type: "input_value", name: "PLAYER" }, { type: "input_value", name: "REASON", check: "String" }],
    previousStatement: null, nextStatement: null, inputsInline: true,
    colour: 290, tooltip: "Remove a player from the server",
  },
  {
    type: "rbx_set_walkspeed", message0: "set walkspeed of %1 to %2",
    args0: [{ type: "input_value", name: "PLAYER" }, { type: "input_value", name: "SPEED", check: "Number" }],
    previousStatement: null, nextStatement: null, inputsInline: true,
    colour: 290, tooltip: "Set a player's humanoid WalkSpeed",
  },
  {
    type: "rbx_set_health", message0: "set health of %1 to %2",
    args0: [{ type: "input_value", name: "PLAYER" }, { type: "input_value", name: "AMOUNT", check: "Number" }],
    previousStatement: null, nextStatement: null, inputsInline: true,
    colour: 290, tooltip: "Set a player's humanoid Health",
  },
  {
    type: "rbx_teleport", message0: "teleport %1 to %2",
    args0: [{ type: "input_value", name: "PLAYER" }, { type: "input_value", name: "TARGET" }],
    previousStatement: null, nextStatement: null, inputsInline: true,
    colour: 290, tooltip: "Move a player to another player",
  },
  {
    type: "rbx_join", message0: "join %1 %2",
    args0: [{ type: "input_value", name: "A" }, { type: "input_value", name: "B" }],
    output: "String", inputsInline: true,
    colour: 160, tooltip: "Join two values into one string",
  },

  {
    type: "ui_set_title", message0: "set window title to %1",
    args0: [{ type: "input_value", name: "TEXT", check: "String" }],
    previousStatement: null, nextStatement: null, inputsInline: true,
    colour: 180, tooltip: "Set the executor window title",
  },
  {
    type: "ui_set_accent", message0: "set accent color r %1 g %2 b %3",
    args0: [
      { type: "input_value", name: "R", check: "Number" },
      { type: "input_value", name: "G", check: "Number" },
      { type: "input_value", name: "B", check: "Number" },
    ],
    previousStatement: null, nextStatement: null, inputsInline: true,
    colour: 180, tooltip: "Recolor the executor accent",
  },
  {
    type: "ui_set_background", message0: "set background color r %1 g %2 b %3",
    args0: [
      { type: "input_value", name: "R", check: "Number" },
      { type: "input_value", name: "G", check: "Number" },
      { type: "input_value", name: "B", check: "Number" },
    ],
    previousStatement: null, nextStatement: null, inputsInline: true,
    colour: 180, tooltip: "Recolor the executor background",
  },
  {
    type: "ui_notify", message0: "show toast %1",
    args0: [{ type: "input_value", name: "TEXT", check: "String" }],
    previousStatement: null, nextStatement: null, inputsInline: true,
    colour: 180, tooltip: "Pop a temporary toast message",
  },
  {
    type: "ui_log", message0: "log %1 to console",
    args0: [{ type: "input_value", name: "TEXT", check: "String" }],
    previousStatement: null, nextStatement: null, inputsInline: true,
    colour: 180, tooltip: "Write a line to the executor console",
  },
  {
    type: "ui_add_button", message0: "add quick button %1",
    args0: [{ type: "input_value", name: "LABEL", check: "String" }],
    previousStatement: null, nextStatement: null, inputsInline: true,
    colour: 180, tooltip: "Add a button to the executor",
  },

  {
    type: "runtime_on_player_added", message0: "when a player joins %1",
    args0: [{ type: "input_dummy" }],
    message1: "do %1", args1: [{ type: "input_statement", name: "DO" }],
    colour: 20, tooltip: "Runs on the server each time a player joins. Use the 'the player' block to refer to them.",
  },
  {
    type: "runtime_on_player_removing", message0: "when a player leaves %1",
    args0: [{ type: "input_dummy" }],
    message1: "do %1", args1: [{ type: "input_statement", name: "DO" }],
    colour: 20, tooltip: "Runs on the server when a player disconnects.",
  },
  {
    type: "runtime_on_request", message0: "when an admin sends a request %1",
    args0: [{ type: "input_dummy" }],
    message1: "do %1", args1: [{ type: "input_statement", name: "DO" }],
    colour: 20, tooltip: "Hook that runs before every request. Use 'reject this request' to deny it.",
  },
  {
    type: "runtime_register_action", message0: "define action %1 %2",
    args0: [
      { type: "field_input", name: "NAME", text: "freeze" },
      { type: "input_dummy" },
    ],
    message1: "do %1", args1: [{ type: "input_statement", name: "DO" }],
    colour: 20, tooltip: "Add a custom action the executor can invoke by name.",
  },
  {
    type: "runtime_the_player", message0: "the player", output: null,
    colour: 270, tooltip: "Refers to the player the surrounding hook is acting on.",
  },
  {
    type: "runtime_request_mode_is", message0: "request is raw lua",
    output: "Boolean", colour: 20,
    tooltip: "True when the incoming request is hand-written Luau (not blocks).",
  },
  {
    type: "runtime_reject_request", message0: "reject this request",
    previousStatement: null,
    colour: 0, tooltip: "Stop the request. Use inside 'when an admin sends a request'.",
  },
  {
    type: "runtime_action_arg", message0: "action arg %1",
    args0: [{ type: "field_input", name: "KEY", text: "duration" }],
    output: null, colour: 20,
    tooltip: "Read a named argument the executor passed when invoking this action.",
  },
  {
    type: "runtime_emit", message0: "send to console %1",
    args0: [{ type: "input_value", name: "TEXT", check: "String" }],
    previousStatement: null, nextStatement: null, inputsInline: true,
    colour: 20, tooltip: "Send a line back to the player who invoked this action.",
  },
]);

const textShadow = (t) => ({ shadow: { type: "text", fields: { TEXT: t } } });
const numShadow = (n) => ({ shadow: { type: "math_number", fields: { NUM: n } } });
const playerShadow = { shadow: { type: "rbx_current_player" } };

window.SCRIPT_TOOLBOX = {
  kind: "categoryToolbox",
  contents: [
    { kind: "category", name: "Output", colour: "200", contents: [
      { kind: "block", type: "rbx_print", inputs: { TEXT: textShadow("hello") } },
      { kind: "block", type: "rbx_warn", inputs: { TEXT: textShadow("careful") } },
    ]},
    { kind: "category", name: "Control", colour: "40", contents: [
      { kind: "block", type: "rbx_wait", inputs: { SECONDS: numShadow(1) } },
      { kind: "block", type: "controls_if" },
      { kind: "block", type: "controls_repeat_ext", inputs: { TIMES: numShadow(10) } },
      { kind: "block", type: "controls_whileUntil" },
    ]},
    { kind: "category", name: "Logic", colour: "210", contents: [
      { kind: "block", type: "logic_compare" },
      { kind: "block", type: "logic_operation" },
      { kind: "block", type: "logic_negate" },
      { kind: "block", type: "logic_boolean" },
    ]},
    { kind: "category", name: "Math", colour: "230", contents: [
      { kind: "block", type: "math_number", fields: { NUM: 0 } },
      { kind: "block", type: "math_arithmetic", inputs: { A: numShadow(1), B: numShadow(1) } },
      { kind: "block", type: "math_modulo", inputs: { DIVIDEND: numShadow(64), DIVISOR: numShadow(10) } },
      { kind: "block", type: "math_random_int", inputs: { FROM: numShadow(1), TO: numShadow(100) } },
    ]},
    { kind: "category", name: "Text", colour: "160", contents: [
      { kind: "block", type: "text" },
      { kind: "block", type: "rbx_join", inputs: { A: textShadow("score: "), B: numShadow(0) } },
    ]},
    { kind: "category", name: "Variables", colour: "330", custom: "VARIABLE" },
    { kind: "category", name: "Players", colour: "270", contents: [
      { kind: "block", type: "rbx_for_each_player" },
      { kind: "block", type: "rbx_current_player" },
      { kind: "block", type: "rbx_find_player", inputs: { NAME: textShadow("Player1") } },
      { kind: "block", type: "rbx_players_count" },
      { kind: "block", type: "rbx_kick", inputs: { PLAYER: playerShadow, REASON: textShadow("Kicked") } },
      { kind: "block", type: "rbx_set_walkspeed", inputs: { PLAYER: playerShadow, SPEED: numShadow(16) } },
      { kind: "block", type: "rbx_set_health", inputs: { PLAYER: playerShadow, AMOUNT: numShadow(100) } },
      { kind: "block", type: "rbx_teleport", inputs: { PLAYER: playerShadow, TARGET: { shadow: { type: "rbx_find_player", inputs: { NAME: textShadow("Player1") } } } } },
    ]},
  ],
};

window.INTERFACE_TOOLBOX = {
  kind: "categoryToolbox",
  contents: [
    { kind: "category", name: "Interface", colour: "180", contents: [
      { kind: "block", type: "ui_set_title", inputs: { TEXT: textShadow("SkidSS") } },
      { kind: "block", type: "ui_set_accent", inputs: { R: numShadow(124), G: numShadow(92), B: numShadow(255) } },
      { kind: "block", type: "ui_set_background", inputs: { R: numShadow(22), G: numShadow(22), B: numShadow(28) } },
      { kind: "block", type: "ui_notify", inputs: { TEXT: textShadow("hello") } },
      { kind: "block", type: "ui_log", inputs: { TEXT: textShadow("ready") } },
      { kind: "block", type: "ui_add_button", inputs: { LABEL: textShadow("Run") } },
    ]},
    { kind: "category", name: "Control", colour: "40", contents: [
      { kind: "block", type: "controls_if" },
      { kind: "block", type: "controls_repeat_ext", inputs: { TIMES: numShadow(3) } },
      { kind: "block", type: "rbx_wait", inputs: { SECONDS: numShadow(1) } },
    ]},
    { kind: "category", name: "Math", colour: "230", contents: [
      { kind: "block", type: "math_number", fields: { NUM: 0 } },
      { kind: "block", type: "math_arithmetic", inputs: { A: numShadow(1), B: numShadow(1) } },
    ]},
    { kind: "category", name: "Text", colour: "160", contents: [
      { kind: "block", type: "text" },
      { kind: "block", type: "rbx_join", inputs: { A: textShadow("count: "), B: numShadow(0) } },
    ]},
    { kind: "category", name: "Variables", colour: "330", custom: "VARIABLE" },
  ],
};

const thePlayerShadow = { shadow: { type: "runtime_the_player" } };

window.RUNTIME_TOOLBOX = {
  kind: "categoryToolbox",
  contents: [
    { kind: "category", name: "Hooks", colour: "20", contents: [
      { kind: "block", type: "runtime_on_player_added" },
      { kind: "block", type: "runtime_on_player_removing" },
      { kind: "block", type: "runtime_on_request" },
      { kind: "block", type: "runtime_register_action" },
    ]},
    { kind: "category", name: "Request", colour: "20", contents: [
      { kind: "block", type: "runtime_request_mode_is" },
      { kind: "block", type: "runtime_reject_request" },
    ]},
    { kind: "category", name: "Action", colour: "20", contents: [
      { kind: "block", type: "runtime_action_arg" },
      { kind: "block", type: "runtime_emit", inputs: { TEXT: textShadow("done") } },
    ]},
    { kind: "category", name: "Players", colour: "270", contents: [
      { kind: "block", type: "runtime_the_player" },
      { kind: "block", type: "rbx_find_player", inputs: { NAME: textShadow("Player1") } },
      { kind: "block", type: "rbx_players_count" },
      { kind: "block", type: "rbx_kick", inputs: { PLAYER: thePlayerShadow, REASON: textShadow("Kicked") } },
      { kind: "block", type: "rbx_set_walkspeed", inputs: { PLAYER: thePlayerShadow, SPEED: numShadow(16) } },
      { kind: "block", type: "rbx_set_health", inputs: { PLAYER: thePlayerShadow, AMOUNT: numShadow(100) } },
      { kind: "block", type: "rbx_teleport", inputs: { PLAYER: thePlayerShadow, TARGET: { shadow: { type: "rbx_find_player", inputs: { NAME: textShadow("Player1") } } } } },
    ]},
    { kind: "category", name: "Output", colour: "200", contents: [
      { kind: "block", type: "rbx_print", inputs: { TEXT: textShadow("hello") } },
      { kind: "block", type: "rbx_warn", inputs: { TEXT: textShadow("careful") } },
    ]},
    { kind: "category", name: "Control", colour: "40", contents: [
      { kind: "block", type: "controls_if" },
      { kind: "block", type: "controls_repeat_ext", inputs: { TIMES: numShadow(3) } },
      { kind: "block", type: "rbx_wait", inputs: { SECONDS: numShadow(1) } },
    ]},
    { kind: "category", name: "Logic", colour: "210", contents: [
      { kind: "block", type: "logic_compare" },
      { kind: "block", type: "logic_operation" },
      { kind: "block", type: "logic_negate" },
      { kind: "block", type: "logic_boolean" },
    ]},
    { kind: "category", name: "Math", colour: "230", contents: [
      { kind: "block", type: "math_number", fields: { NUM: 0 } },
      { kind: "block", type: "math_arithmetic", inputs: { A: numShadow(1), B: numShadow(1) } },
    ]},
    { kind: "category", name: "Text", colour: "160", contents: [
      { kind: "block", type: "text" },
      { kind: "block", type: "rbx_join", inputs: { A: textShadow("score: "), B: numShadow(0) } },
    ]},
    { kind: "category", name: "Variables", colour: "330", custom: "VARIABLE" },
  ],
};
